version: "3"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: always
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./static/:/static